# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculadora.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calculadora.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x61lculadora.proto\x12\x0b\x63\x61lculadora\"D\n\rSolicitudMath\x12\x0f\n\x07numero1\x18\x01 \x01(\x01\x12\x0f\n\x07numero2\x18\x02 \x01(\x01\x12\x11\n\toperacion\x18\x03 \x01(\t\"K\n\rRespuestaMath\x12\x11\n\tresultado\x18\x01 \x01(\x01\x12\x11\n\tesExitoso\x18\x02 \x01(\x08\x12\x14\n\x0cmensajeError\x18\x03 \x01(\t2Y\n\x13ServicioCalculadora\x12\x42\n\x08\x43\x61lcular\x12\x1a.calculadora.SolicitudMath\x1a\x1a.calculadora.RespuestaMathB&\n\x10\x63\x61lculadora.grpcB\x10\x43\x61lculadoraProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculadora_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020calculadora.grpcB\020CalculadoraProtoP\001'
  _globals['_SOLICITUDMATH']._serialized_start=34
  _globals['_SOLICITUDMATH']._serialized_end=102
  _globals['_RESPUESTAMATH']._serialized_start=104
  _globals['_RESPUESTAMATH']._serialized_end=179
  _globals['_SERVICIOCALCULADORA']._serialized_start=181
  _globals['_SERVICIOCALCULADORA']._serialized_end=270
# @@protoc_insertion_point(module_scope)
